version: '3.8'

networks:
  movies:
    name: movies

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: movies.nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      - ./nginx/logs:/var/log/nginx
    networks:
      - movies
    depends_on:
      - php
      - postgres
      - rabbitmq
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: movies.php
    volumes:
      - ./src:/var/www/html
      - ./php/logs:/var/log/php
    user: 1000:www-data
    networks:
      - movies

#  sqlite:
#    build:
#      context: .
#      dockerfile: sqlite.dockerfile
#    container_name: api-movies.sqlite
#    volumes:
#      - ./sqlite:/data
#

  postgres:
    container_name: movies.postgres
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: movies
    volumes:
      - ../storage/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - movies

  rabbitmq:
    image: "rabbitmq:management"
    container_name: movies.rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    networks:
      - movies
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  composer:
    image: composer:latest
    container_name: movies.composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    user: 1000:www-data
    networks:
      - movies

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: movies.artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    user: 1000:www-data
    networks:
      - movies

  npm:
    image: node:current-alpine
    container_name: movies.npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    user: 1000:www-data
    networks:
      - movies

  phpunit:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: movies.phpunit
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "/var/www/html/vendor/bin/phpunit" ]
    user: 1000:www-data
    networks:
      - movies

volumes:
  rabbitmq_data:
    driver: local





