name: Check & fix styling

on:
  push:

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix style
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=src/.php-cs-fixer.php --allow-risky=yes --allow-risky=yes

      - name: Extract branch name
        shell: bash
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Fix styling
          branch: ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: ${{ steps.commit-changes.outputs.changes_detected == 'true' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Fix styling
          branch: ${{ env.branch_name }}
          title: "Fix styling"
          body: "This pull request fixes styling issues."
          base: dev