name: Check & fix styling

on:
  push:

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fix style
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=src/.php-cs-fixer.php --allow-risky=yes --allow-risky=yes

      - name: Commit changes
        with:
          commit_message: Apply php-cs-fixer changes